<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('bookings')->delete();

        \DB::table('bookings')->insert(array (
            0 =>
            array (
                'id' => 1,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:00',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '4',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:04:25',
                'updated_at' => '2025-03-10 01:04:25',
            ),
            1 =>
            array (
                'id' => 2,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:00',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '4',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:06:36',
                'updated_at' => '2025-03-10 01:06:36',
            ),
            2 =>
            array (
                'id' => 3,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:00',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '4',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:09:18',
                'updated_at' => '2025-03-10 01:09:18',
            ),
            3 =>
            array (
                'id' => 4,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:38:08',
                'updated_at' => '2025-03-10 01:38:08',
            ),
            4 =>
            array (
                'id' => 5,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:39:29',
                'updated_at' => '2025-03-10 01:39:29',
            ),
            5 =>
            array (
                'id' => 6,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:39:46',
                'updated_at' => '2025-03-10 01:39:46',
            ),
            6 =>
            array (
                'id' => 7,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:40:20',
                'updated_at' => '2025-03-10 01:40:20',
            ),
            7 =>
            array (
                'id' => 8,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:40:28',
                'updated_at' => '2025-03-10 01:40:28',
            ),
            8 =>
            array (
                'id' => 9,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:40:44',
                'updated_at' => '2025-03-10 01:40:44',
            ),
            9 =>
            array (
                'id' => 10,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:42:16',
                'updated_at' => '2025-03-10 01:42:16',
            ),
            10 =>
            array (
                'id' => 11,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:43:02',
                'updated_at' => '2025-03-10 01:43:02',
            ),
            11 =>
            array (
                'id' => 12,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:44:42',
                'updated_at' => '2025-03-10 01:44:42',
            ),
            12 =>
            array (
                'id' => 13,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:44:59',
                'updated_at' => '2025-03-10 01:44:59',
            ),
            13 =>
            array (
                'id' => 14,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:45:15',
                'updated_at' => '2025-03-10 01:45:15',
            ),
            14 =>
            array (
                'id' => 15,
                'admin_id' => 1,
                'company_id' => 1,
                'customer_id' => 1,
                'from_service' => 'alirajpur',
                'to_service' => 'alirajpur',
                'vehicle_group' => '5',
                'duty_type' => '4',
                'start_date' => '2025-03-10',
                'end_date' => '2025-03-10',
                'reporting_time' => '04:15',
                'drop_time' => '04:15',
                'garage_time' => 60,
                'reporting_address' => 'Plot No 25/N/2, Shivaji Nagar',
                'drop_address' => 'Govandi',
                'short_reporting_address' => NULL,
                'ticket_number' => NULL,
            'bill_to' => 'Company / Customer (Default)',
                'price' => 100,
                'per_extra_km_rate' => NULL,
                'per_extra_hr_rate' => NULL,
                'remarks' => NULL,
                'driver_remark' => NULL,
                'operator_notes' => NULL,
                'labels' => '1',
                'is_confirmed_booking' => 0,
                'created_at' => '2025-03-10 01:48:55',
                'updated_at' => '2025-03-10 01:48:55',
            ),
        ));

    }
}
